# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0004_auto_20170426_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='portresult',
            name='latency',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='portresult',
            name='portNumber',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='portresult',
            name='port_type',
            field=models.CharField(default='tcp', max_length=5),
        ),
        migrations.AlterField(
            model_name='portresult',
            name='state',
            field=models.CharField(default='closed', max_length=20),
        ),
    ]
