# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0008_scanresults_porttoscan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresults',
            old_name='portToScan',
            new_name='firstport',
        ),
        migrations.AddField(
            model_name='scanresults',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 14, 8, 21, 618710)),
        ),
        migrations.AddField(
            model_name='scanresults',
            name='lastport',
            field=models.CharField(default='80', max_length=5),
        ),
    ]
