# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 22:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portscan', '0009_auto_20170429_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresults',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanresults',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 17, 54, 30, 173309)),
        ),
    ]
