# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=70)),
                ('port_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=70)),
                ('scanDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scanresult',
            name='port_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portresult',
            name='assignedScanResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.ScanResults'),
        ),
    ]
