# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0003_remove_scanresults_scandate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.AddField(
            model_name='scanresults',
            name='name',
            field=models.CharField(default='scan name', max_length=250),
        ),
    ]
