# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portscan', '0005_auto_20170427_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portresult',
            name='port_type',
            field=models.CharField(default='undefined', max_length=5),
        ),
        migrations.AlterField(
            model_name='portresult',
            name='service',
            field=models.CharField(default='undefined', max_length=70),
        ),
        migrations.AlterField(
            model_name='portresult',
            name='state',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
